pantsbuild/example-python

README.md, helloworld/util/BUILD, pants.toml
This can serve as some very quick documentation for
someone who just wants to play around without going
through the full docsite.
Also updates some config, notably removing pylint, since
the repo doesn't conform to it.
=> Update the README.

pants.toml
See https://github.com/pantsbuild/pants/issues/9509 for how this is a misfeature that we need to remove.
=> Fix interpreter constraints appending rather than overriding

pants.toml
This requires using the new syntax for source roots at the root level.
We don't upgrade to 1.29.0.dev1 yet because Protobuf is broken.
=> Upgrade to 1.28.0

pants, pants.toml, pants_from_sources
This PR is in preparation for the Pants 2.0.0 release. It's in draft mode because 2.0 is not stable yet, but it could be merged once that changes.
The PR is intended to
(a) serve as a working example for people who want to explore Pants 2.0
(b) show the diff between a working 1.x and 2.0 configuration
Progress:
- ~~Right now, the upgrade to 2.0.0.dev4 still fails: ./pants list :: raises 31 rules errors - any feedback is appreciated~~
- ~~Update: According to @stuhood the failure seems to be related to `protoc` not being ready for 2.0 yet (https://github.com/pantsbuild/pants/issues/10425)~~
- ~~Update 2: Downgrading to 2.0.0.dev2 fixed the issue~~
- Update 3: The new 2.0.0.dev5 fixes the regression, everything seems to work on the latest dev release now
=> Update `pants` and `pants.toml` for 2.0 release

.travis.yml, README.md, helloworld/util/BUILD, pants.ci.toml, pants.toml
=> Upgrade to 2.0.0.dev7

helloworld/BUILD
Otherwise PEP420 implicit namespaces don't work.
=> Make our py3 binary non-zip-safe.

.travis.yml, constraints.txt
Otherwise `./pants run helloworld:helloworld_py2` doesn't work.
=> Add py2 __init__.py files.

pants
Update the `./pants` wrapper to add support for specifying a main branch version of Pants via PANTS_SHA.
=> update ./pants wrapper with PANTS_SHA support

pants.toml
This corresponds to an updated entry for https://www.pantsbuild.org/docs/python-interpreter-compatibility#changing-the-interpreter-search-path.
=> Upgrade to 2.0.0rc1

helloworld/BUILD
See https://github.com/pantsbuild/pants/pull/11176 for why the `sources` field was a bad idea, even though this results in a little more boilerplate.
=> Stop using `sources` field for `python_awslambda`

README.md, helloworld/BUILD, helloworld/greet/BUILD, helloworld/util/BUILD, helloworld/util/proto/BUILD, pants.toml
Thanks to 2.2, we can now use the simplified design for `pex_binary` and `python_awslambda`. They no longer have `sources` fields, but have fields that act like it.
We can also simplify thanks to dep inference for Protobuf.
In the process, we do a better job explaining what each target is precisely doing. This is easier to do now that we have cleared up the responsibility of each target type.
=> Upgrade to 2.2 and improve explanation of targets

.github/workflows/pants.yaml
- Update the GitHub Actions workflow to match the build steps in the current Travis config.
- Enable caching of Pants cache.
=> CI: update GitHub Actions workflow to match Travis config

pants.toml
This will allow us to get green over in the test matrix run by
https://gitlab.com/remote-apis-testing/remote-apis-testing
=> Upgrade to 2.3.1rc0 with remote exec fix.

pants.toml
Also upgrade to 2.6.0rc2, which includes telemetry fixes.
=> Enable anonymous telemetry.

pants_from_sources
If someone wanted to override any of these, they could do so via environment variables. But I've never seen it be necessary to actually commit an edit, because when testing with a wildly different version of Pants, it's usually a temporary measure.
=> Remove plugin/path/backend variables from `pants_from_sources` script.

README.md
It looks me a couple of attempts to successfully follow along from the README.md on a MacBook Pro with Apple Silicon., ultimately coming down to needing to properly configure pants.toml to use pyenv and update the Python interpreter dependency. I believe the statement added to the README.md by this commit will help others in the same situation.
=> Update the README.md for a better experience for MacOS users

.github/workflows/pants.yaml
Links back to the docs and explains why remote caching can be helpful.
=> Better guidance on how to set up CI with Pants.

.github/workflows/pants.yaml
This adjusts the cache keys used in the CI setup based on the improved version from #104. I think there were some typos (e.g. using `pants-setup-...` for the `named_caches` restore key), and it seems that scoping everything under `pants-{name}-...` is nifty.
=> Adjust CI cache key names to be consistent

.github/workflows/pants.yaml, get-pants.sh
This checks in the current `get-pants.sh` script, following the reasonable recommendation from the docs: https://www.pantsbuild.org/docs/installation
> Instead, for regular use, we recommend checking this script into the root of your repo and pointing users and CI machines to that checked-in version
Hopefully having it in this example repo helps encourage users towards this better practice.
=> Check in get-pants.sh script, following doc recommendation

.github/workflows/pants.yaml
The log file is in workdir, according to https://github.com/pantsbuild/pants/blob/44a06c5825e294757fb1dfe5920ea4b81db56023/src/python/pants/init/logging.py#L232 The path referred to in the docs is preceded by workdir: https://github.com/pantsbuild/pants/blob/44a06c5825e294757fb1dfe5920ea4b81db56023/docs/docs/using-pants/using-pants-in-ci.mdx#L240
=> fix path to pants.log

.github/workflows/pants.yaml
The template project currently uses outdated versions of _action/checkout,_ _action/setup-python,_ and _init-pants._ The checkout and setup-python actions cause deprecation warnings in the GitHub workflow.
This PR updates the three mentioned actions to their respective latest versions, which also gets rid of the deprecation warnings.
=> Update GitHub actions to most recent versions

README.md, get-pants.sh, pants.toml
Upgrade to Pants v2.23.0rc1, remove an obsolete config, and update the `get-pants.sh` script.
=> upgrade to Pants v2.23.0rc1 + other fixes
